version: '3.9'
services:
  web:
   build: 
    context: ./web
    target: dev
   ports:
    - '8753:8753'
   restart: always 
   volumes:
    - "./web/logs:/var/log/nginx"
   
  app:
   build:
    context: ./app
    target: dev
   restart: always
   environment: 
      NODE_ENV: test
   
   
   
   

   