FROM nginx:alpine as dev

COPY dlpapidev.conf /etc/nginx/conf.d/

EXPOSE 8753
CMD ["nginx", "-g", "daemon off;"]

FROM dev as test

RUN rm /etc/nginx/conf.d/dlpapidev.conf
COPY dlpapitest.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]

FROM dev as prod

RUN rm /etc/nginx/conf.d/dlpapitest.conf
COPY dlpapiprod.conf /etc/nginx/conf.d/

CMD ["nginx", "-g", "daemon off;"]
