FROM nginx:alpine

#RUN rm /var/log/nginx/*

#RUN ln -sf /dev/stdout /var/log/nginx/access.log \ 	&& ln -sf /dev/stderr /var/log/nginx/error.log
#RUN rm  -f /var/log/nginx/
#RUN mkdir /opt/nginx
#RUN touch /opt/nginx/access.log \ touch /opt/nginx/access.log
#RUN ln -s /var/log/nginx/access.log /opt/nginx/access.log \ ln -s /var/log/nginx/ /opt/nginx/error.log


#RUN rm  /etc/nginx/conf.d/default.conf 
      
#RUN  rm -f /var/log/nginx/* /opt/nginx/*

COPY dlpapi.conf /etc/nginx/conf.d/
#COPY favicon.ico /usr/share/nginx/html/

EXPOSE 8753

#RUN  nginx -t

#WORKDIR /opt/nginx

CMD ["nginx", "-g", "daemon off;"]
